# Copyright 2013 IBM Corp.

ACTIVE = u'ACTIVE'  # PowerVC VM is running
BUILD = u'BUILD'  # PowerVC VM only exists in DB
ERROR = u'ERROR'
SHUTOFF = u'SHUTOFF'
RESIZE = u'RESIZE'
VERIFY_RESIZE = u'VERIFY_RESIZE'
MIGRATING = u' MIGRATING'
